dbtype: sqlite3
dbfilename: sqlite.db

api: true
apiport: 8080
apiserver: localhost
apisecure: false

mtrview:
  count: 1
  timeout: 30
  interval: 5
  maxhops: 20
  maxhops_unknown: 5
  ringbuffer: 50
  ptr_lookup: true
  src_address:
