name: Build go app

on:
  push:
    branches:
    - main
    - develop
    #paths:
    #- 'cmd/*'
    #- 'pkg/*'
    #- 'vendor/*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v1
      with:
        go-version: 1.19
      id: go
    
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: "All updates"
      run: sudo apt-get update && sudo apt-get -y upgrade
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Run build
      run: GOFLAGS=-mod=mod go build -o bin/npv main.go
    
    - name: Run the app
      run: sudo go run ./main.go run single 1.1.1.1

