name: publish-app

on:
  push:
    branches:
    - main
    - develop
    
env:
  NAME: wbontekoe
  REPO: npv
  
jobs: 
  build:
  
    runs-on: ubuntu-latest
  
    steps:

    - name: Check out code
      uses: actions/checkout@v1
               
    - name: Login to DockerHub 
      uses: docker/login-action@v1 
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: Build and push
      uses: docker/build-push-action@v2 
      with:
        context: .
        file: ./Dockerfile 
        push: true
        tags: ${{env.NAME}}/${{env.REPO}}:latest
        