name: Pull Request

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.17', '1.18', '1.19' ]

    steps:

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: "All updates"
      run: sudo apt-get update && sudo apt-get -y upgrade
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Run build
      run: GOFLAGS=-mod=mod go build -o bin/npv main.go
    
    - name: Run the app
      run: sudo go run ./main.go run single 1.1.1.1